name: "publish"
on:
  push:
    branches:
      - release
  workflow_dispatch:
jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""
          - platform: "ubuntu-22.04"
            args: "--target aarch64-unknown-linux-gnu"
            arch: "arm64"
    runs-on: ${{ matrix.platform }}
    env:
      DENO_DIR: deno_cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || matrix.arch == 'arm64' && 'aarch64-unknown-linux-gnu' || '' }}
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
      - name: setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      - name: install frontend dependencies
        run: deno install
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' && matrix.arch != 'arm64' && matrix.arch != 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev
      - name: install dependencies (regular builds)
        if: matrix.platform == 'ubuntu-22.04' && matrix.arch != 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev
          
          # Create complete pkg-config files for cross-compilation
          sudo mkdir -p /usr/lib/aarch64-linux-gnu/pkgconfig
          
          # Create glib-2.0.pc (base dependency)
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/glib-2.0.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: GLib
          Description: C Utility Library
          Version: 2.72.4
          Libs: -L${libdir} -lglib-2.0
          Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include
          EOF
          
          # Create cairo.pc
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/cairo.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: cairo
          Description: Multi-platform 2D graphics library
          Version: 1.16.0
          Libs: -L${libdir} -lcairo
          Cflags: -I${includedir}/cairo
          EOF
          
          # Create pango.pc
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/pango.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: Pango
          Description: Internationalized text handling
          Version: 1.50.6
          Requires: glib-2.0 cairo
          Libs: -L${libdir} -lpango-1.0
          Cflags: -I${includedir}/pango-1.0
          EOF
          
          # Create gdk-pixbuf-2.0.pc
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/gdk-pixbuf-2.0.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: GdkPixbuf
          Description: Image loading and scaling
          Version: 2.42.8
          Requires: glib-2.0
          Libs: -L${libdir} -lgdk_pixbuf-2.0
          Cflags: -I${includedir}/gdk-pixbuf-2.0
          EOF
          
          # Create atk.pc
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/atk.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: Atk
          Description: Accessibility toolkit
          Version: 2.36.0
          Requires: glib-2.0
          Libs: -L${libdir} -latk-1.0
          Cflags: -I${includedir}/atk-1.0
          EOF
          
          # Create gdk-3.0.pc (now with proper dependencies)
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/gdk-3.0.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: GDK
          Description: GTK+ Drawing Kit
          Version: 3.24.33
          Requires: gdk-pixbuf-2.0 pango cairo glib-2.0
          Libs: -L${libdir} -lgdk-3
          Cflags: -I${includedir}/gtk-3.0 -I${includedir}/gtk-3.0/gdk
          EOF
          
          # Create gtk+-3.0.pc
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/gtk+-3.0.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: GTK+
          Description: GTK+ Graphical UI Library
          Version: 3.24.33
          Requires: gdk-3.0 atk cairo glib-2.0 pango gdk-pixbuf-2.0
          Libs: -L${libdir} -lgtk-3
          Cflags: -I${includedir}/gtk-3.0
          EOF
          
          # Create webkit2gtk-4.1.pc
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: WebKit2GTK
          Description: WebKit2GTK+ API
          Version: 2.40.5
          Requires: gtk+-3.0 glib-2.0
          Libs: -L${libdir} -lwebkit2gtk-4.1
          Cflags: -I${includedir}/webkitgtk-4.1
          EOF
          
          # Create javascriptcoregtk-4.1.pc (WebKit JavaScript engine)
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/javascriptcoregtk-4.1.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: JavaScriptCoreGTK
          Description: JavaScript engine from WebKitGTK+
          Version: 2.40.5
          Requires: glib-2.0
          Libs: -L${libdir} -ljavascriptcoregtk-4.1
          Cflags: -I${includedir}/webkitgtk-4.1
          EOF
          
          # Create libsoup-3.0.pc (HTTP client library)
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/libsoup-3.0.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: libsoup
          Description: HTTP client/server library
          Version: 3.0.8
          Requires: glib-2.0
          Libs: -L${libdir} -lsoup-3.0
          Cflags: -I${includedir}/libsoup-3.0
          EOF
          
          # Create gdk-x11-3.0.pc (X11 backend for GDK)
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/gdk-x11-3.0.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: GDK X11
          Description: GTK+ Drawing Kit for X11
          Version: 3.24.33
          Requires: gdk-3.0
          Libs: -L${libdir} -lgdk-3 -lX11
          Cflags: -I${includedir}/gtk-3.0 -I${includedir}/gtk-3.0/gdk
          EOF
          
          # Create OpenSSL pkg-config files
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/openssl.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: OpenSSL
          Description: Secure Sockets Layer and cryptography libraries
          Version: 3.0.2
          Libs: -L${libdir} -lssl -lcrypto
          Cflags: -I${includedir}/openssl
          EOF
          
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/libssl.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: OpenSSL-libssl
          Description: Secure Sockets Layer library
          Version: 3.0.2
          Requires: libcrypto
          Libs: -L${libdir} -lssl
          Cflags: -I${includedir}/openssl
          EOF
          
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/libcrypto.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: OpenSSL-libcrypto
          Description: OpenSSL cryptography library
          Version: 3.0.2
          Libs: -L${libdir} -lcrypto
          Cflags: -I${includedir}/openssl
          EOF
          
          # Create minimal OpenSSL headers directory
          sudo mkdir -p /usr/aarch64-linux-gnu/usr/include/openssl
          sudo touch /usr/aarch64-linux-gnu/usr/include/openssl/opensslconf.h
          
          # Create additional required .pc files
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/libappindicator3-0.1.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: appindicator3-0.1
          Description: Application indicators
          Version: 0.4.92
          Requires: gtk+-3.0
          Libs: -L${libdir} -lappindicator3
          Cflags: -I${includedir}/libappindicator3-0.1
          EOF
          
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/librsvg-2.0.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: librsvg
          Description: SVG library
          Version: 2.52.5
          Requires: gdk-pixbuf-2.0 cairo glib-2.0
          Libs: -L${libdir} -lrsvg-2
          Cflags: -I${includedir}/librsvg-2.0
          EOF
          
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/libudev.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: libudev
          Description: udev library
          Version: 249
          Libs: -L${libdir} -ludev
          Cflags: -I${includedir}
          EOF
          
          echo "Complete pkg-config setup for ARM64 cross-compilation created"
      - name: Set cross-compilation environment (ARM64)
        if: false  # Disabled - using Docker for ARM64 builds
        run: |
          echo "ARM64 builds are handled by Docker - skipping cross-compilation setup"
      - name: Build ARM64 using cross-compilation
        if: matrix.platform == 'ubuntu-22.04' && matrix.arch == 'arm64'
        run: |
          # Install cross-compilation toolchain
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu pkg-config
          
          # Install Rust target
          rustup target add aarch64-unknown-linux-gnu
          
          # Set up environment for cross-compilation
          export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
          export CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++
          export AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          export PKG_CONFIG_ALLOW_CROSS=1
          
          # Force Rust to use vendored OpenSSL to avoid cross-compilation issues
          export OPENSSL_STATIC=1
          export OPENSSL_VENDORED=1
          export OPENSSL_NO_PKG_CONFIG=1
          
          # Create minimal .cargo/config.toml
          mkdir -p .cargo
          cat > .cargo/config.toml << 'EOF'
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          EOF
          
          # Build with explicit vendored OpenSSL
          cd src-tauri
          cargo build --release --target aarch64-unknown-linux-gnu
          
          # Create a simple bundle structure
          mkdir -p target/release/bundle/deb
          
          # Copy the binary to a known location for artifact upload
          mkdir -p ../artifacts
          cp target/aarch64-unknown-linux-gnu/release/opendeck ../artifacts/opendeck-arm64 || true
          ls -la target/aarch64-unknown-linux-gnu/release/
      
      - name: Upload ARM64 artifacts
        if: matrix.platform == 'ubuntu-22.04' && matrix.arch == 'arm64'
        uses: actions/upload-artifact@v4
        with:
          name: tauri-artifacts-arm64
          path: artifacts/*
      
      - uses: tauri-apps/tauri-action@v0
        if: matrix.platform != 'ubuntu-22.04' || matrix.arch != 'arm64'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: deno task tauri
          tagName: tv__VERSION__
          releaseName: "OpenDeck v__VERSION__"
          releaseBody: "See the assets to download this version. See the README for installation instructions."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
