name: "publish"
on:
  push:
    branches:
      - release
  workflow_dispatch:
jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""
          - platform: "ubuntu-22.04"
            args: "--target aarch64-unknown-linux-gnu"
            arch: "arm64"
    runs-on: ${{ matrix.platform }}
    env:
      DENO_DIR: deno_cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || matrix.arch == 'arm64' && 'aarch64-unknown-linux-gnu' || '' }}
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
      - name: setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      - name: install frontend dependencies
        run: deno install
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' && matrix.arch != 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev
      - name: install dependencies (ARM64 cross-compilation)
        if: matrix.platform == 'ubuntu-22.04' && matrix.arch == 'arm64'
        run: |
          # Install cross-compilation toolchain
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross pkg-config
          
          # Download and manually install ARM64 .pc files and headers needed for GTK/WebKit
          mkdir -p /tmp/arm64-deps
          cd /tmp/arm64-deps
          
          # Create minimal pkg-config files for cross-compilation
          sudo mkdir -p /usr/lib/aarch64-linux-gnu/pkgconfig
          
          # Create a minimal gdk-3.0.pc file that will satisfy the build requirements
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/gdk-3.0.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: GDK
          Description: GTK+ Drawing Kit
          Version: 3.24.33
          Requires: gdk-pixbuf-2.0 >= 2.30.0 pango >= 1.44.0 cairo >= 1.14.0
          Libs: -L${libdir} -lgdk-3
          Cflags: -I${includedir}/gtk-3.0 -I${includedir}/gdk-pixbuf-2.0 -I${includedir}/pango-1.0 -I${includedir}/cairo
          EOF
          
          # Create other essential .pc files
          sudo tee /usr/lib/aarch64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc << 'EOF'
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib/aarch64-linux-gnu
          includedir=${prefix}/include
          
          Name: WebKit2GTK
          Description: WebKit2GTK+ API
          Version: 2.40.5
          Requires: gtk+-3.0 glib-2.0 libsoup-3.0
          Libs: -L${libdir} -lwebkit2gtk-4.1
          Cflags: -I${includedir}/webkitgtk-4.1
          EOF
          
          echo "Minimal cross-compilation setup complete"
      - name: Set cross-compilation environment (ARM64)
        if: matrix.platform == 'ubuntu-22.04' && matrix.arch == 'arm64'
        run: |
          echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
          echo "AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1" >> $GITHUB_ENV
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: deno task tauri
          tagName: tv__VERSION__
          releaseName: "OpenDeck v__VERSION__"
          releaseBody: "See the assets to download this version. See the README for installation instructions."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
